try {
 // try block
		int a=12;
		throw a;
		cout<<"something";
 
 
}
catch (float arg){ 
// catch block
}
catch (string arg){ 
// catch block
}
catch (int arg){ 
// catch block
} 
. 
.
.
catch (student arg){ 
cout<<arg.name();
// catch block
}
cout<<"continue";
return 0;
